### ISSUE TITLE
Missing comma makes JSON invalid

### ISSUE THREAD

**Issue by jjg-dressipi** [nhsx/covid19-app-system-public#1]
In [this line](https://github.com/nhsx/covid19-app-system-public/blob/a41ee3c966c4f59ff0b1e7c3ff8aeb70b1c2d312/test/data/test-data-descriptions.json#L29).  I guess this file is not (yet) used in anger :smile:

**Comment by nhs-covid19** [comment]
Thanks for your interest in the NHS Covid-19 project. Yes - it does look like this JSON file is invalid. We'll check if this file is still required and remove or fix it as needed.
