### ISSUE TITLE
Broken link in Architecture guidebook

### ISSUE THREAD

**Issue by NRKirby** [nhsx/covid19-app-system-public#10]
In the Architecture guide, the link about the GAEN framework under the **Functional and technical domains** is broken, i.e. this link:

https://static.googleusercontent.com/media/www.google.com/en//covid19/exposurenotifications/pdfs/Android-Exposure-Notification-API-documentation-v1.3.2.pdf

**Comment by bobwhitelock** [comment]
Fixed in https://github.com/nhsx/covid19-app-system-public/pull/6

**Comment by nhs-covid19** [comment]
Thanks for your interest in the NHS Covid-19 project. We'll be looking at the links in the documentation and try to make sure they are consistent. Thanks for pointing this out.
