### ISSUE TITLE
Using US Region for resources

### ISSUE THREAD

**Issue by cdjg35** [nhsx/covid19-app-system-public#12]
**Describe the bug**
Cloudfront appears to use US resources

**To Reproduce**
web_acl.tf has
data "aws_wafv2_web_acl" "this" {
  name     = var.waf2_web_acl
  scope    = "CLOUDFRONT"
  provider = aws.us_east
}

provider "aws" {
  alias  = "us_east"
  region = "us-east-1"
}
**Expected behavior**
data "aws_wafv2_web_acl" "this" {
  name     = var.waf2_web_acl
  scope    = "CLOUDFRONT"
  provider = aws.eu-west
}

provider "aws" {
  alias  = "eu-west"
  region = "eu-west-2"
}

**Comment by beezly** [comment]
@cdjg35 This looks correct. Configuration of cloudfront WAF resources is done through us-east-1. https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/wafv2_web_acl#scope has more info.
