### ISSUE TITLE
'Contact tracing' cannot be enabled on iOS 14.0.1

### ISSUE THREAD

**Issue by acrostich** [nhsx/covid19-app-system-public#13]
The 'Contact Tracing' setting is switched off and remains switched off even after trying to switch it on

1. Open the app
2. Try to enable Contact tracing by clicking the greyed switch
3. Choose an option (4 hours, 8 hours, 12 hours or Don't remind me), same with any of them.
4. Contact tracing remains off. 

After clicking that switch I'd expect Contact tracing to be on.

![IMG_9547](https://user-images.githubusercontent.com/1878811/94274279-66bd6e80-ff3d-11ea-9e4f-065ae44d1d58.jpg)

 - Device: iPhone 11
 - OS: iOS 14.01.1

Bluetooth is on and I tried after rebooting the phone too.

**Comment by acrostich** [comment]
It's now working with the latest update v3.6.1

**Comment by InternalLoss** [comment]
If it now works, you should close the issue.

**Comment by acrostich** [comment]
It's working for me, but I thought the developers would close it after confirming that it was fixed and not just a coincidence. However I'll close it.

**Comment by InternalLoss** [comment]
I don't think the developers are actively responding to Issues here (probably some weird thing they're not allowed to discuss); plus, it probably checks OS or does other weird stuff (it might have been Apple forcing an update for EN stuff, who knows?)
