### ISSUE TITLE
Scenarios and Decisions missing

### ISSUE THREAD

**Issue by paulchambers** [nhsx/covid19-app-system-public#14]
The Architecture Guidebook mentions scenarios and decisions but both are missing from the repo.

Are these documents intended to be public? 

**To Reproduce**
Browse to https://github.com/nhsx/covid19-app-system-public/blob/master/doc/architecture/ag-architecture-guidebook.md#quality-scenarios-and-decisions
Click "current scenarios" or "Architectural Decision Records ADRs"

**Expected behavior**
The scenarios or decisions are displayed

**Actual Behavior**
404 page

**Comment by nhs-covid19** [comment]
Thanks for your interest in the NHS Covid-19 project. We'll be looking at the links in the documentation and try to make sure they are consistent. Thanks for pointing this out. 
When we fix the issue upstream it will become available in this repository at the next software release.

**Comment by paulchambers** [comment]
Hi, This isn't a missing link it is that the docs simply aren't in the repo.
