### ISSUE TITLE
postDistricts value an object or array?

### ISSUE THREAD

**Issue by vls29** [nhsx/covid19-app-system-public#15]
https://github.com/nhsx/covid19-app-system-public/blob/a41ee3c966c4f59ff0b1e7c3ff8aeb70b1c2d312/src/static/risky-post-districts.json#L2

Hi,

Is postDistricts in the above code snippet supposed to be an object or array?

**Comment by nhs-covid19** [comment]
Thanks for your interest in the NHS Covid-19 project. This is a mapping from postcode to risk level, so a JSON object seems like a suitable data structure.
