### ISSUE TITLE
Accessing aggregated data

### ISSUE THREAD

**Issue by LucaciPaul** [nhsx/covid19-app-system-public#18]
Hi!

Is it possible to access aggregated data stored for analytics? If so, how can one do that?

Apparently, the API link from documentation is broken, although I am unsure if that is the right place to find the answer.

For educational and research purposes.

**Comment by nhs-covid19** [comment]
Thanks for your interest in the NHS Covid-19 project. Currently the analytics data is available only to specifically authorised individuals within the programme, and there are no plans to make this data more widely available.
