### ISSUE TITLE
elif unreachable

### ISSUE THREAD

**Issue by jjg-dressipi** [nhsx/covid19-app-system-public#2]
The condition in [this line](https://github.com/nhsx/covid19-app-system-public/blob/a41ee3c966c4f59ff0b1e7c3ff8aeb70b1c2d312/src/aws/lambdas/advanced_analytics/advanced_analytics.py#L72) will never be triggered since it is subsumed by the `if`; any number greater than 500 is already greater than 300. Perhaps replace the `elif` by an `if`.

**Comment by nhs-covid19** [comment]
Thanks for your interest in the NHS Covid-19 project. Yes - it looks like the specific error message for a 5xx error won't be logged, although a generic error message will be. We'll figure out if the specific 5xx message adds any value, and fix it as required. Good Spot!
