### ISSUE TITLE
Minor - Best practice improvement - Check: CKV_AWS_52: "Ensure S3 bucket has MFA delete enabled"

### ISSUE THREAD

**Issue by dewhurstwill** [nhsx/covid19-app-system-public#22]
Check: CKV_AWS_52: "Ensure S3 bucket has MFA delete enabled"
	FAILED for resource: aws_s3_bucket.this
	File: /src/aws/libraries/conpan_s3/main.tf:5-37
	Guide: https://docs.bridgecrew.io/docs/bc_aws_s3_24

Check: CKV_AWS_52: "Ensure S3 bucket has MFA delete enabled"
	FAILED for resource: aws_s3_bucket.this
	File: /src/aws/libraries/repository_s3/main.tf:9-36
	Guide: https://docs.bridgecrew.io/docs/bc_aws_s3_24

Check: CKV_AWS_52: "Ensure S3 bucket has MFA delete enabled"
	FAILED for resource: aws_s3_bucket.this
	File: /src/aws/libraries/analytics_s3/main.tf:7-51
	Guide: https://docs.bridgecrew.io/docs/bc_aws_s3_24

Check: CKV_AWS_52: "Ensure S3 bucket has MFA delete enabled"
	FAILED for resource: aws_s3_bucket.destination
	File: /src/aws/libraries/submission_s3/main.tf:89-106
	Guide: https://docs.bridgecrew.io/docs/bc_aws_s3_24

**To Reproduce**
1. Install https://github.com/bridgecrewio/checkov (Checkov is a static code analysis tool for infrastructure-as-code.)

**Expected behavior**
Previously failed steps pass

**Comment by nhs-covid19** [comment]
Thanks for your interest in the NHS Covid-19 project. A wide variety of security and policy scanning tools are used on the source code and the runtime systems for the application, and the output from these systems is fed back into the development process.  All signals will be evaluated, and scheduled for remediation according to priority.
