### ISSUE TITLE
Minor - Best practice improvement - Check: CKV_AWS_76: "Ensure API Gateway has Access Logging enabled"

### ISSUE THREAD

**Issue by dewhurstwill** [nhsx/covid19-app-system-public#24]
Check: CKV_AWS_76: "Ensure API Gateway has Access Logging enabled"
	FAILED for resource: aws_apigatewayv2_stage.this
	File: /src/aws/libraries/submission_api_gateway/main.tf:35-46
	Guide: https://docs.bridgecrew.io/docs/logging_17

**To Reproduce**
1. Install https://github.com/bridgecrewio/checkov (Checkov is a static code analysis tool for infrastructure-as-code.)

**Expected behavior**
Previously failed steps pass

**Comment by nhs-covid19** [comment]
Thanks for your interest in the NHS Covid-19 project. A wide variety of security and policy scanning tools are used on the source code and the runtime systems for the application, and the output from these systems is fed back into the development process.  All signals will be evaluated, and scheduled for remediation according to priority.
This is a specific example of a policy that needs to be applied selectively. Various design decisions are made across the application to improve user privacy and anonymity.
