### ISSUE TITLE
Minor - Best practice improvement - Check: CKV_AWS_34: "Ensure cloudfront distribution ViewerProtocolPolicy is set to HTTPS"

### ISSUE THREAD

**Issue by dewhurstwill** [nhsx/covid19-app-system-public#26]
Check: CKV_AWS_34: "Ensure cloudfront distribution ViewerProtocolPolicy is set to HTTPS"
	FAILED for resource: aws_cloudfront_distribution.this
	File: /src/aws/libraries/cloudfront_conpan_facade/main.tf:20-99
	Guide: https://docs.bridgecrew.io/docs/networking_32

**To Reproduce**
1. Install https://github.com/bridgecrewio/checkov (Checkov is a static code analysis tool for infrastructure-as-code.)

**Expected behavior**
Previously failed steps pass

**Comment by nhs-covid19** [comment]
Thanks for your interest in the NHS Covid-19 project. A wide variety of security and policy scanning tools are used on the source code and the runtime systems for the application, and the output from these systems is fed back into the development process. All signals will be evaluated, and scheduled for remediation according to priority.
