### ISSUE TITLE
Link to API contract in repo readme.md is 404

### ISSUE THREAD

**Issue by Relequestual** [nhsx/covid19-app-system-public#3]
> The API contracts for all exposed endpoints based on a small number of patterns.

The "API contracts" link results in a 404 page.
Content missing.

**Comment by bobwhitelock** [comment]
Fixed in https://github.com/nhsx/covid19-app-system-public/pull/4 (at least based on the file movements and renames in https://github.com/nhsx/covid19-app-system-public/commit/a41ee3c966c4f59ff0b1e7c3ff8aeb70b1c2d312).

**Comment by thefisk** [comment]
You beat me to it, Bob  :)

**Comment by enly1** [comment]
Worth calling out that there are many other broken links in the readme documents - https://github.com/nhsx/covid19-app-system-public/tree/master/src/aws for example, /src/aws/accounts, src/aws links are all broken - maybe worth a quick scan across the rest.

**Comment by Relequestual** [comment]
I just wanted to see what was being used =]
Avro is OK I guess.
Wanted to see OpenAPI or JSON Schema!

**Comment by Krusty93** [comment]
`API Contracts` and `Pattern` links are still broken

**Comment by Relequestual** [comment]
@Krusty93 the PR is not yet merged.

**Comment by nhs-covid19** [comment]
Thanks for your interest in the NHS Covid-19 project. We'll be looking at the links in the documentation and try to make sure they are consistent. Thanks for pointing this out.
