### ISSUE TITLE
Should the design documentation repo for the beta be archived?

### ISSUE THREAD

**Issue by Jazzyboy1** [nhsx/covid19-app-system-public#7]
Hey. I've noticed that this repository is still open: https://github.com/nhsx/COVID-19-app-Documentation-BETA
Looking at PRs and issues on other repos, it sounds like you've changed the design a lot since that repo was last updated.

So is that repo still up to date? And if not, perhaps you should archive it? I was a little confused this morning whilst trying to look through your source code repositories for design docs.

Do the docs in this repository (https://github.com/nhsx/covid19-app-system-public) now cover all of the architectural design?

P.S. Sorry for raising this here rather than there. It seems I can't raise issues in that repository.

**Comment by nhs-covid19** [comment]
Thanks for your interest in the NHS Covid-19 project. This is a good suggestion. The iOS and Android repos are already archived, but the documentation repo isn't. We'll archive it.
All architectural documentation for the current application is in this repository, except for any specific internal software architecture documentation for the mobile applications which will be in the relevant mobile application repo.
