### ISSUE TITLE
No keys from before 2 days prior to onset of symptoms

### ISSUE THREAD

**Issue by hoehleatsu** [nhsx/covid19-app-system-public#9]
**Describe the bug**
In [TransmissionRiskLevelApplier.kt](https://github.com/nhsx/covid-19-app-android-ag-public/blob/01f790a0ebefe20ba6ff7925e56dfd88911741bf/app/src/main/java/uk/nhs/nhsx/covid19/android/app/exposure/TransmissionRiskLevelApplier.kt#L56) I see the following:

```
// COV-3804: We don't want keys from before 2 days prior to onset of symptoms
private const val PRIOR_DAYS_THRESHOLD = -2
```

Is this choice of -2 days in sync with the corrected version of [He et al. (2020)](https://www.nature.com/articles/s41591-020-1016-z) ?

**Expected behavior**
In their recommendation they write: _Therefore, from a contact-tracing viewpoint, it may be adequate to enquire about close contacts up to 3 days before the index first shows symptoms_.  So

```
private const val PRIOR_DAYS_THRESHOLD = -3
```

seems a more natural choice? Or how is the -2 motivated?

**Comment by ChrisJBurns** [comment]
I think this is one of the biggest worries about the app. Many people will be concerned that they get told to self-isolate on these figures. So a decision on this should not be taken lightly :+1:

**Comment by nhs-covid19** [comment]
Thanks for your interest in the NHS Covid-19 project. We are working closely with a number of research organisations, as well as  with Apple and Google on the development of their APIs, and the correct risk parameters to apply. The parameterisation of any API calls represents the best available advice at the time, and will be updated as and when this advice is updated.

**Comment by hoehleatsu** [comment]
Thank you for the reply, which unfortunately provides little information. 

Could you as part of your transparency effort please provide 1-2 references/sources which the choice of -2 days is based on?
